//
//  AddAccountWorker.swift
//  PLAN-IT
//
//  Created by KiwiTech on 28/08/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
class AddAccountWorker {
    let apiStore = AddAccountApiStore()
    func sendPlaidToken(request: AddAccount.Request, completion: @escaping Completion<UserResponse>) throws {
        apiStore.sendPlaidToken(request: request, completion: completion)
    }
}
