//
//  AddAccountRouter.swift
//  PLAN-IT
//
//  Created by KiwiTech on 28/08/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AddAccountRoutingLogic {
}

protocol AddAccountDataPassing {
  var dataStore: AddAccountDataStore? { get }
}

class AddAccountRouter: NSObject, AddAccountRoutingLogic, AddAccountDataPassing {
  weak var viewController: AddAccountViewController?
  var dataStore: AddAccountDataStore?
}
