//
//  WelcomeWorker.swift
//  PLAN-IT
//
//  Created by KiwiTech on 23/07/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
class WelcomeWorker {
    let apiStore = WelcomeApiStore()
    func getAssessmentQuestions(completion: @escaping Completion<AssesmentResponse>)throws {
        apiStore.getAssessmentQuestions(completion: completion)
    }
}
