//
//  WelcomeInteractor.swift
//  PLAN-IT
//
//  Created by KiwiTech on 23/07/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WelcomeBusinessLogic {
  func getAssessmentQuestions()
}

protocol WelcomeDataStore {
  //var name: String { get set }
}

class WelcomeInteractor: WelcomeBusinessLogic, WelcomeDataStore {
  var presenter: WelcomePresentationLogic?
  var worker: WelcomeWorker?
    func getAssessmentQuestions() {
        if worker == nil {
            worker = WelcomeWorker()
        }
        do {
            try worker?.getAssessmentQuestions(completion: {[weak self] (response) in
                self?.presenter?.handle(response: response)
            })
        } catch let error {
            handle(exception: error)
        }
    }
    fileprivate func handle(exception: Error) {
      presenter?.showError(text: .somethingWentWrong + "\n" + .tryAgainInTime)
    }
}
