//
//  VerificationResetModels.swift
//  PLAN-IT
//
//  Created by KiwiTech on 12/07/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum VerificationReset {
  // MARK: Use cases
    struct Request {
    }
    struct Response {
        var email: String?
        var isFromSignUp: Bool?
        init(email: String? = nil, isFromSignUp: Bool? = nil) {
            self.email = email
            self.isFromSignUp = isFromSignUp
        }
    }
    struct ViewModel {
        var email: String?
        var isFromSignUp: Bool?
        init(email: String? = nil, isFromSignUp: Bool? = nil) {
            self.email = email
            self.isFromSignUp = isFromSignUp
        }
    }
}
