//
//  AssessmentModels.swift
//  PLAN-IT
//
//  Created by KiwiTech on 19/07/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
enum Assessment {
  // MARK: Use cases
    struct Request: ParameterConvertible {
        var category1: Int?
        var category2: Int?
        var category3: Int?
        init(category1: Int? = nil, category2: Int? = nil,
             category3: Int? = nil) {
            self.category1 = category1
            self.category2 = category2
            self.category3 = category3
        }
    }
    struct Response {
    }
    struct ViewModel {
    }
}
