//
//  AssessmentPresenter.swift
//  PLAN-IT
//
//  Created by KiwiTech on 19/07/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
protocol AssessmentPresentationLogic {
    func presentAssessmentQuestion(question: [Category]?)
    func showError(text: String)
    func handle(response: Response<UserResponse>)
}

class AssessmentPresenter: AssessmentPresentationLogic {
  weak var viewController: AssessmentDisplayLogic?
  // MARK: Do something
    func presentAssessmentQuestion(question: [Category]?) {
        viewController?.getAssessmentQuestions(value: question)
    }
    func showError(text: String) {
        viewController?.showAlertFor(text: text)
    }
    func handle(response: Response<UserResponse>) {
        if response.isSuccess, let value = response.value {
            viewController?.scoreSend(data: value.data ?? UserData())
        } else {
            let msg = NetworkManager.shared.errorString(from: response)
            viewController?.showAlertFor(text: msg ?? .failedTo(.proceed) + "\n" + .tryAgainInTime)
        }
    }
}
