//
//  AssessmentRouter.swift
//  PLAN-IT
//
//  Created by KiwiTech on 19/07/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AssessmentRoutingLogic {
}

protocol AssessmentDataPassing {
  var dataStore: AssessmentDataStore? { get set }
}

class AssessmentRouter: NSObject, AssessmentRoutingLogic, AssessmentDataPassing {
  weak var viewController: AssessmentViewController?
  var dataStore: AssessmentDataStore?
}
