//
//  LoginWorker.swift
//  i-Mar
//
//  Created by KiwiTech on 01/07/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
enum LoginErrors: Error {
    case invalidEmail,
    blankField
}
class LoginWorker {
    let apiStore = LoginApiStore()
    func login(request: Login.Request, completion: @escaping Completion<UserResponse>) throws {
        apiStore.login(request: request, completion: completion)
    }
}
