//
//  LoginModels.swift
//  i-Mar
//
//  Created by KiwiTech on 01/07/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login {
    struct Request: ParameterConvertible {
        var email: String?
        var password: String?
        init(email: String? = nil, password: String? = nil) {
            self.email = email
            self.password = password
        }
    }
    struct Response: ParameterConvertible {
    }
    struct ViewModel: ParameterConvertible {
    }
}
