//
//  LoginPresenter.swift
//  i-Mar
//
//  Created by KiwiTech on 01/07/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
protocol LoginPresentationLogic {
    func showError(text: String)
    func handle(response: Response<UserResponse>)
    func showValidationError(text: String)
}

class LoginPresenter: LoginPresentationLogic {
    weak var viewController: LoginDisplayLogic?
    func showError(text: String) {
        viewController?.showAlertFor(text: text)
    }
    func handle(response: Response<UserResponse>) {
        if response.isSuccess, let value = response.value {
            if value.data?.isVerified == true {
                AppStateManager.shared.hasLoggedIn = true
                UserDefaults.standard.removeValue(for: .initialViewController)
                if let userData = value.data {
                    viewController?.loginCompleted(data: userData)
                }
            } else {
                viewController?.loginNotVerified()
            }
        } else {
            let msg  = NetworkManager.shared.errorString(from: response) ?? .failedTo(.signin) + "\n" + .tryAgainInTime
            viewController?.showAlertFor(text: msg)
        }
    }
    func showValidationError(text: String) {
        viewController?.validationFailed(with: text)
    }
}
