//
//  CreatePinModels.swift
//  PLAN-IT
//
//  Created by KiwiTech on 04/09/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
enum CreatePin {
  // MARK: Use cases
    struct Request: ParameterConvertible {
        var pin: Int?
        init(pin: Int? = nil) {
            self.pin = pin
        }
    }
    struct Response {
    }
    struct ViewModel {
    }
}
