//
//  CreatePinWorker.swift
//  PLAN-IT
//
//  Created by KiwiTech on 04/09/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
class CreatePinWorker {
    let apiStore = CreatePinApiStore()
    func createPin(request: CreatePin.Request, completion: @escaping Completion<UserResponse>) throws {
        apiStore.createPin(request: request, completion: completion)
    }
    func verifyPin(request: CreatePin.Request, completion: @escaping Completion<StaticMessgaeResponse>) throws {
        apiStore.verifyPin(request: request, completion: completion)
    }
}
