//
//  CreatePinInteractor.swift
//  PLAN-IT
//
//  Created by KiwiTech on 04/09/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreatePinBusinessLogic {
  func createPin(request: CreatePin.Request)
  func verifyPin(request: CreatePin.Request)
}

protocol CreatePinDataStore {
  //var name: String { get set }
}

class CreatePinInteractor: CreatePinBusinessLogic, CreatePinDataStore {
  var presenter: CreatePinPresentationLogic?
  var worker: CreatePinWorker?
  // MARK: Do something
    func createPin(request: CreatePin.Request) {
        if worker == nil {
            worker = CreatePinWorker()
        }
        do {
            try worker?.createPin(request: request, completion: {[weak self] (response) in
                self?.presenter?.handle(response: response)
            })
        } catch let error {
            handle(exception: error)
        }
    }
    func verifyPin(request: CreatePin.Request) {
        if worker == nil {
            worker = CreatePinWorker()
        }
        do {
            try worker?.verifyPin(request: request, completion: {[weak self] (response) in
                self?.presenter?.handleVerify(response: response)
            })
        } catch let error {
            handle(exception: error)
        }
    }
    fileprivate func handle(exception: Error) {
        presenter?.showError(text: .somethingWentWrong + "\n" + .tryAgainInTime)
    }
}
