//
//  AccountModels.swift
//  PLAN-IT
//
//  Created by KiwiTech on 07/08/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Account {
  // MARK: Use cases
    struct Request {
        var promoCode: String?
        init(promoCode: String? = nil) {
            self.promoCode = promoCode
        }
    }
    struct DeActivatePostRequst: ParameterConvertible {
        var id: Int = AppStateManager.shared.user?.id ?? 0
    }
    struct ChangePushPostRequst: ParameterConvertible {
        var id: Int = AppStateManager.shared.user?.id ?? 0
        var pushStatus: PushStatus?
        init() {
            self.pushStatus = PushStatus(
                emailNotification: AppStateManager.shared.user?.emailNotification,
                pushNotification: AppStateManager.shared.user?.pushNotification
            )
        }
    }
    struct Response {
    }
    struct ViewModel {
    }
}
