//
//  AccountRouter.swift
//  PLAN-IT
//
//  Created by KiwiTech on 07/08/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AccountRoutingLogic {
    func redirectToChangePassword()
    func redirectToSubscriptionPopUp()
}

protocol AccountDataPassing {
  var dataStore: AccountDataStore? { get }
}

class AccountRouter: NSObject, AccountRoutingLogic, AccountDataPassing {
  weak var viewController: AccountViewController?
  var dataStore: AccountDataStore?
    // MARK: - Redirect Screens
    func redirectToChangePassword() {
        let controller = AppUtils.viewController(with: ChangePasswordViewController.identifier, in: .tabbar)
        viewController?.hidesBottomBarWhenPushed = true
        viewController?.navigationController?.pushViewController(controller, animated: true)
        viewController?.hidesBottomBarWhenPushed = false
    }
    func redirectToSubscriptionPopUp() {
        let controller = AppUtils.viewController(with: SubscriptionGuidPopUpViewController.identifier, in: .tabbar)
        self.viewController?.showAsPopUp(controller: controller)
    }
}
