//
//  LessonListRouter.swift
//  PLAN-IT
//
//  Created by KiwiTech on 08/08/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LessonListRoutingLogic {
}

protocol LessonListDataPassing {
  var dataStore: LessonListDataStore? { get set }
}

class LessonListRouter: NSObject, LessonListRoutingLogic, LessonListDataPassing {
  weak var viewController: LessonListViewController?
  var dataStore: LessonListDataStore?
}
