//
//  LessonListWorker.swift
//  PLAN-IT
//
//  Created by KiwiTech on 08/08/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
class LessonListWorker {
    let apiStore = LessonListApiStore()
    func getLessonDetail(lessonId: Int, completion: @escaping Completion<LessonDetailResponse>) throws {
        apiStore.getLessonDetail(lessonId: lessonId, completion: completion)
    }
    func lessonRead(lessonId: Int, completion: @escaping Completion<StaticMessgaeResponse>) throws {
        apiStore.lessonRead(lessonId: lessonId, completion: completion)
    }
}
