//
//  AllTransactionsPresenter.swift
//  PLAN-IT
//
//  Created by KiwiTech on 30/08/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AllTransactionsPresentationLogic {
  func presentSomething(response: AllTransactions.Response)
}

class AllTransactionsPresenter: AllTransactionsPresentationLogic {
  weak var viewController: AllTransactionsDisplayLogic?
  // MARK: Do something
  func presentSomething(response: AllTransactions.Response) {
    let viewModel = AllTransactions.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
