//
//  AllTransactionsRouter.swift
//  PLAN-IT
//
//  Created by KiwiTech on 30/08/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AllTransactionsRoutingLogic {
}

protocol AllTransactionsDataPassing {
  var dataStore: AllTransactionsDataStore? { get set }
}

class AllTransactionsRouter: NSObject, AllTransactionsRoutingLogic, AllTransactionsDataPassing {
  weak var viewController: AllTransactionsViewController?
  var dataStore: AllTransactionsDataStore?
}
