//
//  AllTransactionsModels.swift
//  PLAN-IT
//
//  Created by KiwiTech on 30/08/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum AllTransactions {
  // MARK: Use cases
    struct Request {
        var toDate: String?
        var fromDate: String?
        init(toDate: String? = nil, fromDate: String? = nil) {
            self.toDate = toDate
            self.fromDate = fromDate
        }
    }
    struct Response {
    }
    struct ViewModel {
    }
}
