//
//  TransactionListModels.swift
//  PLAN-IT
//
//  Created by KiwiTech on 03/09/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
enum TransactionList {
  // MARK: Use cases
    struct Request: ParameterConvertible {
        var categoryId: Int?
        var startDate: String?
        var endDate: String?
        var isFromDatePicker: Bool?
        init(categoryId: Int? = nil, startDate: String? = nil, endDate: String? = nil, isFromDatePicker: Bool? = nil) {
            self.categoryId = categoryId
            self.startDate = startDate
            self.endDate = endDate
            self.isFromDatePicker = isFromDatePicker
        }
    }
    struct Response {
    }
    struct ViewModel {
    }
}
