//
//  TransactionListPresenter.swift
//  PLAN-IT
//
//  Created by KiwiTech on 03/09/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
protocol TransactionListPresentationLogic {
    func showError(text: String)
    func handle(response: Response<TransactionResponse>)
    func handlePortfolioTransaction(response: Response<PortfolioTransactionResponse>)
}

class TransactionListPresenter: TransactionListPresentationLogic {
    weak var viewController: TransactionListDisplayLogic?
    func showError(text: String) {
        viewController?.showAlertFor(text: text)
    }
    func handle(response: Response<TransactionResponse>) {
        if response.isSuccess, let value = response.value {
            viewController?.fetchTransaction(data: value.data)
        } else {
            let msg = NetworkManager.shared.errorString(from: response)
            viewController?.showAlertFor(text: msg ?? .failedTo(.proceed) + "\n" + .tryAgainInTime)
        }
    }
    func handlePortfolioTransaction(response: Response<PortfolioTransactionResponse>) {
        if response.isSuccess, let value = response.value {
            viewController?.fetchPortfolioTransaction(data: value.data)
        } else {
            let msg = NetworkManager.shared.errorString(from: response)
            viewController?.showAlertFor(text: msg ?? .failedTo(.proceed) + "\n" + .tryAgainInTime)
        }
    }
}
