//
//  TransactionListWorker.swift
//  PLAN-IT
//
//  Created by KiwiTech on 03/09/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
class TransactionListWorker {
    let apiStore = TransactionListApiStore()
    func fetchTransaction(request: TransactionList.Request, completion: @escaping Completion<TransactionResponse>) throws {
        apiStore.fetchTransaction(request: request, completion: completion)
    }
    func fetchPortfolioTransaction(request: TransactionList.Request, completion: @escaping Completion<PortfolioTransactionResponse>) throws {
        apiStore.fetchPortfolioTransaction(request: request, completion: completion)
    }
}
