//
//  TransactionListRouter.swift
//  PLAN-IT
//
//  Created by KiwiTech on 03/09/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol TransactionListRoutingLogic {
}

protocol TransactionListDataPassing {
  var dataStore: TransactionListDataStore? { get set }
}

class TransactionListRouter: NSObject, TransactionListRoutingLogic, TransactionListDataPassing {
  weak var viewController: TransactionListViewController?
  var dataStore: TransactionListDataStore?
}
