//
//  Strings.swift
//  i-Mar
//
//  Created by KiwiTech on 28/06/19.
//  Copyright © 2019 KiwiTech. All rights reserved.
//

import Foundation
import UIKit

extension String {
    static let okOption = "OK"
    static let yesOption = "Yes"
    static let noOption = "No"
    static let noInternet = "There seems to be an error with your internet connection!"
    static let failedTo: (String) -> String = { (value) in
        return "Failed to \(value)"
    }
    static let accountLinked = "Account has been linked"
    static let accounts = "Link your account"
    static let add = "Add"
    static let appName = "AppName"
    static let underDevlopment = "Under Development!"
    static let date = "Date"
    static let amount = "Amount"
    static let resetPin = "Reset PIN"
    static let restore = "Restore"
    static let HowDoICancelMySubscription = "How do I cancel my subscription?"
    static let deActivateLinkedAccounts = "Deactivate linked accounts"
    static let tryAgainInTime = "Please try again after sometime."
    static let bearer = "Bearer"
    static let signin = "sign in"
    static let signup = "sign up"
    static let lessonFeedback = "lesson feedback"
    static let incorrectEmail = "Incorrect Email !"
    static let somethingWentWrong = "Something went wrong."
    static let done = "Done"
    static let select = "Select"
    static let cancel = "Cancel"
    static let privacyPolicyText = "By signing up you agree to our Terms of service and Privacy policy"
    static let terms = "Terms of service"
    static let term = "Terms of Service"
    static let policy = "Privacy policy"
    static let policies = "Privacy Policy"
    static let termsLink = "https://www.instacart.com"
    static let policyLink = "https://www.google.com"
    static let blankFields = "Fields are empty!"
    static let blankField = "Field is empty!"
    static let invalidFormat = "Invalid Format!"
    static let emailSent = "Email Sent!"
    static let proceed = "proceed"
    static let oldPasswordDoesNotMatch = "Old password doesn't match."
    static let mandatoryFields = "Please fill in the required fields."
    static let resendText = "Trouble getting the link? Resend"
    static let resend = "Resend"
    static let resendLink = "resend"
    static let linkSent = "Link Sent!"
    static let linkSentDescription = "A link to reset your password has been sent to your registered email address. Please follow the instructions given in the email carefully to reset your password and you’ll be able to sign in to your account again."
    static let emailSentDescription = "A verification email has been sent to "
    static let verifyEmailText = ". Please verify your email to continue."
    static let show = "Show"
    static let emoji = "emoji"
    static let welcomeDescription = "PLAN-IT would like to get to know you better. You will complete a short assessment based on the following categories: Financial Psychology, Savings & Budgeting Accounts, and Entrepreneurship."
    static let hiText = "Hi"
    static let passwordInvalid = "Password must contain min. 8 characters."
    static let category = "CATEGORY"
    static let startCoursesDesc = "Based on your assessment score, we have shortlisted %d courses to help you grow your financial knowledge."
    static let startCourseDesc = "Based on your assessment score, we have shortlisted %d course to help you grow your financial knowledge."
    static let read = "READ"
    static let readVideo = "READ & VIDEO"
    static let subscriptionText = "By placing this order, you agree to PLAN-IT’s Terms of Service and Privacy Policy. Your iTunes Account will be charged %@ each month. Subscription automatically renews unless auto-renew is turned off at least 24-hours before the end of the current period. You can manage your subscription and turn off auto-renew from your iTunes Account settings."
    static let descText = "Congrats %@, you are now a subscribed member of PLAN-IT with unlimited access to all of our financial lessons tailored just for you!"
    static let fiveToTenText = "Based on your results, this is an area of opportunity for growth. PLAN-IT will create a personalized path the help you improve."
    static let elevenToFifteenText = "You scored in the \"Intermediate\" range. PLAN-IT will create a personalized path to help you take your knowledge to the next level."
    static let sixteenToTwentyText = "Good job! You scored in the \"Advanced\" range. PLAN-IT will create a personalized path to help you grow even more."
    static let createPinTitle = "Create a PIN"
    static let createPinDesc = "For a better and secure experience on PLAN-IT, please create a 4-digit PIN. You will have to enter this PIN to view all your transactions and will keep your data secured."
    static let resetPinTitle = "Reset PIN"
    static let resetPinDesc = "Not feeling secure with your current PIN? You can reset it here."
    static let enterPinTitle = "Enter your PIN"
    static let enterPinDesc = "Enter your 4 digit PIN to view all your Transactions from last month."
    static let startEndError = "Please check the selected date."
    static let dateFormat = "MMM dd, yyyy"
    static let budgetDateFormat = "yyyy-MM-dd'T'HH:mm:ss.SSSSSS"
    static let checking = "Checking"
    static let saving = "Saving"
    static let portfolio = "Portfolio"
    static let emergencyFund = "Emergency Fund"
    static let housing = "Housing"
    static let debt = "Debt"
    static let utilities = "Utilities"
    static let groceries = "Groceries"
    static let entertainment = "Leisure"
    static let noDataChart = "You need to provide data for the chart."
    static let chartColor = "#f1fff9"
    static let lastMonthTrans = "Distribution for %@ Transactions"
    static let pending = "Pending"
    static let cleared = "Cleared"
    static let setBudgetText = "Set a Budget for %@!"
    static let overSpentText = "How to control this situation?"
    static let budgetSetText = "%@ left for this month."
    static let budgetText = "You have %@ left for this month."
    static let nextMonthText = "You can set your next budget on 1st of %@."
    static let setbudgetCurrentMonthText = "This budget is for %@. You will be able to edit any set budget until the 7th of the month."
    static let budgetOverSpent = "Budget Overspent!"
    static let annualPlaceHolder = "Annual Income($)"
    static let setBudgetPlaceHolder = "$/month"
    static let budgetTitleText = "Set a Budget for %@"
    static let libraryDescsText = "You have %d items saved in your personal library."
    static let libraryDescText = "You have %d item saved in your personal library."
    static let libraryEmptyText = "You have no offline content in your library at this moment."
    static let courseEmptyText = "We couldn’t find any available courses for your score level."
    static let transactionEmptyText = "We couldn’t find any transactions from the last month."
    static let saved = "Saved"
    static let saveToLibrary = "Save to Library"
    static let removeFromLibrary = "Remove from Library"
    static let removeLibrary = "Remove from Library?"
    static let removeThisLesson = "You will not be able to find this read when you are offline."
    static let downloadInProgress = "Download in progress…"
    static let videoError = "Video format is not supported."
    static let noChartData = "No chart data available for last month."
    static let subscriptionUnlockText = "Get access to all the lessons in your courses by subscribing & get started."
    static let purchaseSubscription = "Purchase subscription for %@/month"
    static let subscription = "Subscription"
    static let subscribeToUnlock = "Subscribe to Unlock"
    static let cancelled = "cancelled"
    static let signOut = "Sign Out?"
    static let removeAccount = "Deactivate Account?"
    static let deactivate = "Deactivate"
    static let removeAccountText = "If you deactivate your account, your transaction history will be discarded."
    static let signOutDesc = "Are you sure you want to sign out of the application?"
    static let connectionError = "Connection Error?"
    static let error = "Error?"
    static let connectionErrorDesc = "Some error with your internet connection! Please try again."
    static let userId = "user_id"
    static let userName = "user_name"
    static let userSubscribed = "PLAN_IT_Subscription_Purchased"
    static let setBudget = "PLAN_IT_Budget_Set"
    static let categoryName = "category_name"
    static let saveLibrary = "PLAN_IT_Save_To_Library"
    static let lessonName = "lesson_name"
    static let lessonId = "lesson_id"
    static let categoryId = "category_id"
    static let courseSelected = "PLAN_IT_Course_Opened"
    static let courseName = "course_name"
    static let courseId = "course_id"
    static let coursesTabbed = "PLAN_IT_Course_Tab"
    static let budgetTabbed = "PLAN_IT_Budget_Tab"
    static let libraryTabbed = "PLAN_IT_Library_Tab"
    static let accountTabbed = "PLAN_IT_Account_Tab"
    static let login = "PLAN_IT_Login"
    static let subscribedText = "Your subscription will automatically renew on %@. Currently you are subscribed to a monthly plan of %@."
    static let dntForget = "Don't forget! Mark each lesson as complete to jump to the next."
    static let yayyText = "Yayy! Enjoy all your lessons for free. Don't forget to mark each lesson as complete before moving to next."
    static let expireText = "Expires on %@. After this date you will have to subscribe."
    static let soundsGood = "Sounds Good"
    static let supportSubject = "PLAN-IT | Support Query"
}
extension String {
    var htmlToAttributedString: NSAttributedString? {
        guard let data = data(using: .utf8) else { return NSAttributedString() }
        do {
            return try NSAttributedString(data: data, options: [.documentType: NSAttributedString.DocumentType.html, .characterEncoding: String.Encoding.utf8.rawValue], documentAttributes: nil)
        } catch {
            return NSAttributedString()
        }
    }
    var htmlToString: String {
        return htmlToAttributedString?.string ?? ""
    }
}
