//
//  CourseListPresenter.swift
//  PLAN-IT
//
//  Created by KiwiTech on 02/08/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
protocol CourseListPresentationLogic {
    func showError(text: String)
    func handle(response: Response<CourseListResponse>)
    func handleLessonList(response: Response<LessonListResponse>)
    func handleNewCourse(response: Response<StaticMessgaeResponse>)
}

class CourseListPresenter: CourseListPresentationLogic {
  weak var viewController: CourseListDisplayLogic?
    func showError(text: String) {
        viewController?.showAlertFor(text: text)
    }
    func handle(response: Response<CourseListResponse>) {
        if response.isSuccess, let value = response.value {
            viewController?.fetchedCourseList(data: value.data)
        } else {
            let msg = NetworkManager.shared.errorString(from: response)
            viewController?.showAlertFor(text: msg ?? .failedTo(.proceed) + "\n" + .tryAgainInTime)
        }
    }
    func handleLessonList(response: Response<LessonListResponse>) {
        if response.isSuccess, let value = response.value {
            viewController?.fetchedlessonList(data: value.data)
        } else {
            let msg = NetworkManager.shared.errorString(from: response)
            viewController?.showAlertFor(text: msg ?? .failedTo(.proceed) + "\n" + .tryAgainInTime)
        }
    }
    func handleNewCourse(response: Response<StaticMessgaeResponse>) {
        if response.isSuccess, let value = response.value {
            viewController?.checkNewResponse(response: value.detail ?? "")
        } else {
            let msg = NetworkManager.shared.errorString(from: response)
            viewController?.showAlertFor(text: msg ?? .failedTo(.proceed) + "\n" + .tryAgainInTime)
        }
    }
}
