//
//  CourseListWorker.swift
//  PLAN-IT
//
//  Created by KiwiTech on 02/08/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
class CourseListWorker {
    let apiStore = CourseListApiStore()
    func getCourseList(completion: @escaping Completion<CourseListResponse>) throws {
        apiStore.getCourselist(completion: completion)
    }
    func getLessonlist(courseId: Int, completion: @escaping Completion<LessonListResponse>) throws {
        apiStore.getLessonlist(courseId: courseId, completion: completion)
    }
    func checkNewCourse(courseId: Int, completion: @escaping Completion<StaticMessgaeResponse>) throws {
        apiStore.checkNewCourse(courseId: courseId, completion: completion)
    }
}
