//
//  ScoreInteractor.swift
//  PLAN-IT
//
//  Created by KiwiTech on 01/08/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ScoreBusinessLogic {
    func getScore()
}

protocol ScoreDataStore {
    var assessmentScore: [Int]? { get set }
}

class ScoreInteractor: ScoreBusinessLogic, ScoreDataStore {
    var assessmentScore: [Int]?
    var presenter: ScorePresentationLogic?
    var worker: ScoreWorker?
    // MARK: Do something
    func getScore() {
        presenter?.getScore(assessmentScore: assessmentScore)
    }
}
