//
//  EnterPasswordInteractor.swift
//  PLAN-IT
//
//  Created by KiwiTech on 06/09/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EnterPasswordBusinessLogic {
    func enterPassword(for password: String)
}

protocol EnterPasswordDataStore {
  //var name: String { get set }
}

class EnterPasswordInteractor: EnterPasswordBusinessLogic, EnterPasswordDataStore {
  var presenter: EnterPasswordPresentationLogic?
  var worker: EnterPasswordWorker?
    func enterPassword(for password: String) {
        if worker == nil {
            worker = EnterPasswordWorker()
        }
        do {
            try worker?.enterPassword(password: password, completion: {[weak self] (response) in
                self?.presenter?.handle(response: response)
            })
        } catch let error {
            handle(exception: error)
        }
    }
    fileprivate func handle(exception: Error) {
        presenter?.showError(text: .somethingWentWrong + "\n" + .tryAgainInTime)
    }
}
