//
//  LaunchInteractor.swift
//  PLAN-IT
//
//  Created by KiwiTech on 29/08/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LaunchBusinessLogic {
  func getUserData()
}

protocol LaunchDataStore {
  //var name: String { get set }
}

class LaunchInteractor: LaunchBusinessLogic, LaunchDataStore {
  var presenter: LaunchPresentationLogic?
  var worker: LaunchWorker?
    func getUserData() {
        if worker == nil {
            worker = LaunchWorker()
        }
        do {
            try worker?.getUserData(completion: {[weak self] (response) in
                self?.presenter?.handle(response: response)
            })
        } catch let error {
            handle(exception: error)
        }
    }
    fileprivate func handle(exception: Error) {
        presenter?.showError(text: .somethingWentWrong + "\n" + .tryAgainInTime)
    }
}
