//
//  LaunchPresenter.swift
//  PLAN-IT
//
//  Created by KiwiTech on 29/08/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
protocol LaunchPresentationLogic {
    func showError(text: String)
    func handle(response: Response<UserResponse>)
}

class LaunchPresenter: LaunchPresentationLogic {
  weak var viewController: LaunchDisplayLogic?
  // MARK: Do something
    func showError(text: String) {
        viewController?.showAlertFor(text: text)
    }
    func handle(response: Response<UserResponse>) {
        if response.isSuccess, let value = response.value {
            viewController?.fetchUserData(data: value.data)
        } else {
            let msg = NetworkManager.shared.errorString(from: response)
            viewController?.showAlertFor(text: msg ?? .failedTo(.proceed) + "\n" + .tryAgainInTime)
        }
    }
}
