//
//  SearchCoursePresenter.swift
//  PLAN-IT
//
//  Created by KiwiTech on 19/08/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchCoursePresentationLogic {
    func handleSearchList(response: Response<SearchListResponse>)
    func handleLessonList(response: Response<LessonListResponse>)
}

class SearchCoursePresenter: SearchCoursePresentationLogic {
  weak var viewController: SearchCourseDisplayLogic?

    func handleSearchList(response: Response<SearchListResponse>) {
        if response.isSuccess, let value = response.value {
            viewController?.fetchedSearchList(data: value.results)
        } else {
            let msg = NetworkManager.shared.errorString(from: response)
            if msg != String.cancelled {
                viewController?.showAlertFor(text: msg ?? .failedTo(.proceed) + "\n" + .tryAgainInTime)
            }
        }
    }
    func handleLessonList(response: Response<LessonListResponse>) {
        if response.isSuccess, let value = response.value {
            viewController?.fetchedlessonList(data: value.data)
        } else {
            let msg = NetworkManager.shared.errorString(from: response)
            viewController?.showAlertFor(text: msg ?? .failedTo(.proceed) + "\n" + .tryAgainInTime)
        }
    }
}
