//
//  SearchCourseInteractor.swift
//  PLAN-IT
//
//  Created by KiwiTech on 19/08/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchCourseBusinessLogic {
    func searchCourse(with request: SearchCourse.Request)
    func getLessonList(courseId: Int)
}

protocol SearchCourseDataStore {
  //var name: String { get set }
}

class SearchCourseInteractor: SearchCourseBusinessLogic, SearchCourseDataStore {
  var presenter: SearchCoursePresentationLogic?
  var worker: SearchCourseWorker?
  //var name: String = ""

    // MARK: Do something
    func searchCourse(with request: SearchCourse.Request) {
        if worker == nil {
            worker = SearchCourseWorker()
        }
        do {
            try worker?.searchCourse(request: request, completion: {[weak self] (response) in
                self?.presenter?.handleSearchList(response: response)
            })
        } catch let error {
            handle(exception: error)
        }
    }
    fileprivate func handle(exception: Error) {
        //presenter?.showError(text: .somethingWentWrong + "\n" + .tryAgainInTime)
    }
    func getLessonList(courseId: Int) {
        if worker == nil {
            worker = SearchCourseWorker()
        }
        do {
            try worker?.getLessonlist(courseId: courseId, completion: {[weak self] (response) in
                self?.presenter?.handleLessonList(response: response)
            })
        } catch let error {
            handle(exception: error)
        }
    }
}
