//
//  SearchCourseWorker.swift
//  PLAN-IT
//
//  Created by KiwiTech on 19/08/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
enum SearchCourseErrors: Error {
    case noResultFound
}
class SearchCourseWorker {
    let apiStore = SearchCourseApiStore()
    func searchCourse(request: SearchCourse.Request, completion: @escaping Completion<SearchListResponse>) throws {
        apiStore.searchCourseFromServer(request: request, completion: completion)
    }
    func getLessonlist(courseId: Int, completion: @escaping Completion<LessonListResponse>) throws {
        apiStore.getLessonlist(courseId: courseId, completion: completion)
    }
}
