//
//  LessonDetailInteractor.swift
//  PLAN-IT
//
//  Created by KiwiTech on 13/08/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LessonDetailBusinessLogic {
    func fetchLessonDetail()
    func completeLesson(request: LessonDetail.Request)
}

protocol LessonDetailDataStore {
    var lessonObj: Lesson? { get set }
    var nextLessonId: Int? { get set }
}

class LessonDetailInteractor: LessonDetailBusinessLogic, LessonDetailDataStore {
    var presenter: LessonDetailPresentationLogic?
    var worker: LessonDetailWorker?
    var lessonObj: Lesson?
    var nextLessonId: Int?
    func fetchLessonDetail() {
        presenter?.fetchLessonDetail(lesson: lessonObj, nextlessonId: nextLessonId)
    }
    func completeLesson(request: LessonDetail.Request) {
        if worker == nil {
            worker = LessonDetailWorker()
        }
        do {
            try worker?.completeLesson(request: request, completion: {[weak self] (response) in
                self?.presenter?.handle(response: response)
            })
        } catch let error {
            handle(exception: error)
        }
    }
    fileprivate func handle(exception: Error) {
        presenter?.showError(text: .somethingWentWrong + "\n" + .tryAgainInTime)
    }
}
