//
//  LessonDetailPresenter.swift
//  PLAN-IT
//
//  Created by KiwiTech on 13/08/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
protocol LessonDetailPresentationLogic {
    func fetchLessonDetail(lesson: Lesson?, nextlessonId: Int?)
    func showError(text: String)
    func handle(response: Response<StaticMessgaeResponse>)
}

class LessonDetailPresenter: LessonDetailPresentationLogic {
  weak var viewController: LessonDetailDisplayLogic?
  // MARK: Do something
    func fetchLessonDetail(lesson: Lesson?, nextlessonId: Int?) {
        viewController?.fetchLessonDetail(lesson: lesson, nextlessonId: nextlessonId)
    }
    func showError(text: String) {
        viewController?.showAlertFor(text: text)
    }
    func handle(response: Response<StaticMessgaeResponse>) {
        if response.isSuccess {
            viewController?.lessonCompleted()
        } else {
            let msg = NetworkManager.shared.errorString(from: response)
            viewController?.showAlertFor(text: msg ?? .failedTo(.proceed) + "\n" + .tryAgainInTime)
        }
    }
}
