//
//  LessonDetailModels.swift
//  PLAN-IT
//
//  Created by KiwiTech on 13/08/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
enum LessonDetail {
  // MARK: Use cases
    struct Request: ParameterConvertible {
        var lessonId: Int?
        var nextLessonId: Int?
        init(lessonId: Int? = nil, nextLessonId: Int? = nil) {
            self.lessonId = lessonId
            self.nextLessonId = nextLessonId
        }
    }
    struct Response {
    }
    struct ViewModel {
    }
}
