//
//  ChangePasswordPresenter.swift
//  PLAN-IT
//
//  Created by KiwiTech on 27/09/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChangePasswordPresentationLogic {
    func presentHandleChangePassword(response: Response<UserResponse>)
    func showError(text: String)
}

class ChangePasswordPresenter: ChangePasswordPresentationLogic {
    weak var viewController: ChangePasswordDisplayLogic?
    func presentHandleChangePassword(response: Response<UserResponse>) {
        if response.isSuccess, let value = response.value {
            self.viewController?.changePasswordSuccess(detail: value.detail)
        } else {
            let msg = NetworkManager.shared.errorString(from: response)
            self.viewController?.showAlertFor(text: msg ?? .failedTo(.proceed) + "\n" + .tryAgainInTime)
        }
    }
    func showError(text: String) {
        self.viewController?.showAlertFor(text: text)
    }
}
