//
//  ChangePasswordWorker.swift
//  PLAN-IT
//
//  Created by KiwiTech on 27/09/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ChangePasswordWorker {
    let apiStore = ChangePasswordApiStore()
    func changePassword(postRequest: ChangePassword.ChangePasswordPostRequest, completion: @escaping Completion<UserResponse>) throws {
        apiStore.changePassword(postRequest: postRequest, completion: completion)
    }
}
