//
//  ChangePasswordInteractor.swift
//  PLAN-IT
//
//  Created by KiwiTech on 27/09/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChangePasswordBusinessLogic {
    func changePassword(postRequest: ChangePassword.ChangePasswordPostRequest)
}

protocol ChangePasswordDataStore {
    //var name: String { get set }
}

class ChangePasswordInteractor: ChangePasswordBusinessLogic, ChangePasswordDataStore {
    var presenter: ChangePasswordPresentationLogic?
    var worker: ChangePasswordWorker?
    func changePassword(postRequest: ChangePassword.ChangePasswordPostRequest) {
        if self.worker == nil {
            worker = ChangePasswordWorker()
        }
        do {
            try self.worker?.changePassword(postRequest: postRequest, completion: { (response) in
                self.presenter?.presentHandleChangePassword(response: response)
            })
        } catch let error {
            handle(exception: error)
        }
    }
    fileprivate func handle(exception: Error) {
        self.presenter?.showError(text: .somethingWentWrong + "\n" + .tryAgainInTime)
    }
}
