//
//  ChangePasswordRouter.swift
//  PLAN-IT
//
//  Created by KiwiTech on 27/09/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ChangePasswordRoutingLogic {
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol ChangePasswordDataPassing {
  var dataStore: ChangePasswordDataStore? { get }
}

class ChangePasswordRouter: NSObject, ChangePasswordRoutingLogic, ChangePasswordDataPassing {
  weak var viewController: ChangePasswordViewController?
  var dataStore: ChangePasswordDataStore?
}
