//
//  SetAnnualIncomeWorker.swift
//  PLAN-IT
//
//  Created by KiwiTech on 16/09/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
class SetAnnualIncomeWorker {
    let apiStore = SetAnnualIncomeApiStore()
    func setAnnualIncome(request: SetAnnualIncome.Request, completion: @escaping Completion<UserResponse>) throws {
        apiStore.setAnnualIncome(request: request, completion: completion)
    }
}
