//
//  SetAnnualIncomeRouter.swift
//  PLAN-IT
//
//  Created by KiwiTech on 16/09/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SetAnnualIncomeRoutingLogic {
}

protocol SetAnnualIncomeDataPassing {
  var dataStore: SetAnnualIncomeDataStore? { get }
}

class SetAnnualIncomeRouter: NSObject, SetAnnualIncomeRoutingLogic, SetAnnualIncomeDataPassing {
  weak var viewController: SetAnnualIncomeViewController?
  var dataStore: SetAnnualIncomeDataStore?
}
