//
//  SetAnnualIncomeInteractor.swift
//  PLAN-IT
//
//  Created by KiwiTech on 16/09/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SetAnnualIncomeBusinessLogic {
    func setAnnualIncome(request: SetAnnualIncome.Request)
}

protocol SetAnnualIncomeDataStore {
    //var name: String { get set }
}

class SetAnnualIncomeInteractor: SetAnnualIncomeBusinessLogic, SetAnnualIncomeDataStore {
    var presenter: SetAnnualIncomePresentationLogic?
    var worker: SetAnnualIncomeWorker?
    // MARK: Do something
    func setAnnualIncome(request: SetAnnualIncome.Request) {
        if worker == nil {
            worker = SetAnnualIncomeWorker()
        }
        do {
            try worker?.setAnnualIncome(request: request, completion: {[weak self] (response) in
                self?.presenter?.handleSetAnnualIncome(response: response)
            })
        } catch let error {
            handle(exception: error)
        }
    }
    fileprivate func handle(exception: Error) {
        presenter?.showError(text: .somethingWentWrong + "\n" + .tryAgainInTime)
    }
}
