//
//  SetAnnualIncomePresenter.swift
//  PLAN-IT
//
//  Created by KiwiTech on 16/09/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
protocol SetAnnualIncomePresentationLogic {
    func showError(text: String)
    func handleSetAnnualIncome(response: Response<UserResponse>)
}

class SetAnnualIncomePresenter: SetAnnualIncomePresentationLogic {
    weak var viewController: SetAnnualIncomeDisplayLogic?
    func showError(text: String) {
        viewController?.showAlertFor(text: text)
    }
    func handleSetAnnualIncome(response: Response<UserResponse>) {
        if response.isSuccess, let value = response.value {
            viewController?.setAnnualIncome(data: value.data)
        } else {
            let msg = NetworkManager.shared.errorString(from: response)
            viewController?.showAlertFor(text: msg ?? .failedTo(.proceed) + "\n" + .tryAgainInTime)
        }
    }
}
