//
//  SignUpModels.swift
//  PLAN-IT
//
//  Created by KiwiTech on 08/07/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum SignUp {
    struct Request: ParameterConvertible {
        var firstName: String?
        var lastName: String?
        var dob: String?
        var email: String?
        var password: String?
        init(firstName: String? = nil, lastName: String? = nil, dob: String? = nil, email: String? = nil, password: String? = nil) {
            self.firstName = firstName
            self.lastName = lastName
            self.dob = dob
            self.email = email
            self.password = password
        }
    }
    struct Response: ParameterConvertible {
    }
    struct ViewModel: ParameterConvertible {
    }
    enum Fields {
        case username,
        password
    }
}
