//
//  SignUpRouter.swift
//  PLAN-IT
//
//  Created by KiwiTech on 08/07/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SignUpRoutingLogic {
    func showVerificationScreen(email: String?)
}

protocol SignUpDataPassing {
    var dataStore: SignUpDataStore? { get set }
}

class SignUpRouter: NSObject, SignUpRoutingLogic, SignUpDataPassing {
    weak var viewController: SignUpViewController?
    var dataStore: SignUpDataStore?
    func showVerificationScreen(email: String?) {
        if let verificationVC = AppUtils.viewController(with: VerificationResetViewController.identifier) as? VerificationResetViewController {
            verificationVC.router?.dataStore?.modelObj = VerificationReset.ViewModel(email: email, isFromSignUp: true)
            viewController?.navigationController?.pushViewController(verificationVC, animated: true)
        }
    }
}
