//
//  SignUpWorker.swift
//  PLAN-IT
//
//  Created by KiwiTech on 08/07/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
class SignUpWorker {
    fileprivate let apiStore = SignUpApiStore()
    func signupUser(request: SignUp.Request, completion: @escaping (Response<UserData>) -> Void) throws {
        try validate(request: request)
        apiStore.signup(with: request, completion: completion)
    }
    func validate(request: SignUp.Request) throws {
        //
        guard let email = request.email, ValidationUtils.validateEmail(emailID: email) else {
            throw SignUpErrors.invalidEmail
        }
    }
}
enum SignUpErrors: Error {
    case invalidEmail
}
