//
//  SignUpPresenter.swift
//  PLAN-IT
//
//  Created by KiwiTech on 08/07/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
protocol SignUpPresentationLogic {
    func showError(text: String)
    func handle(response: Response<UserData>)
    func showValidationError(text: String)
}

class SignUpPresenter: SignUpPresentationLogic {
    weak var viewController: SignUpDisplayLogic?
    func handle(response: Response<UserData>) {
        if response.isSuccess, let value = response.value {
            viewController?.signupCompleted(with: value)
        } else {
            let msg  = NetworkManager.shared.errorString(from: response) ?? .failedTo(.signup) + "\n" + .tryAgainInTime
            viewController?.showAlert(for: msg)
        }
    }
    func showError(text: String) {
        viewController?.showAlert(for: text)
    }
    func showValidationError(text: String) {
        viewController?.validationFailed(with: text)
    }
    fileprivate func handle(exception: Error) {
        switch exception {
        case SignUpErrors.invalidEmail:
            viewController?.show(error: "", for: .username)
        default:
            viewController?.show(error: "", for: .username)
        }
    }
}
