//
//  ForgotRouter.swift
//  PLAN-IT
//
//  Created by KiwiTech on 12/07/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ForgotRoutingLogic {
    func showVerificationScreen(email: String?)
}

protocol ForgotDataPassing {
  var dataStore: ForgotDataStore? { get }
}

class ForgotRouter: NSObject, ForgotRoutingLogic, ForgotDataPassing {
  weak var viewController: ForgotViewController?
  var dataStore: ForgotDataStore?
    func showVerificationScreen(email: String?) {
        if let verificationVC = AppUtils.viewController(with: VerificationResetViewController.identifier) as? VerificationResetViewController {
            verificationVC.router?.dataStore?.modelObj = VerificationReset.ViewModel(email: email, isFromSignUp: false)
            viewController?.navigationController?.pushViewController(verificationVC, animated: true)
        }
    }
}
