//
//  ForgotWorker.swift
//  PLAN-IT
//
//  Created by KiwiTech on 12/07/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
class ForgotWorker {
    let apiStore = ForgotApiStore()
    func forgotPassword(for email: String?, completion: @escaping Completion<Details>) throws {
        guard let email = email, ValidationUtils.validateEmail(emailID: email) else {
            throw LoginErrors.invalidEmail
        }
        apiStore.forgotPassword(email: email, completion: completion)
    }
}
