//
//  LessonFeedbackPresenter.swift
//  PLAN-IT
//
//  Created by KiwiTech on 09/08/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
protocol LessonFeedbackPresentationLogic {
    func showRateExperienceWith(categoryName: String?)
    func handle(response: Response<UserResponse>)
    func showError(text: String)
}

class LessonFeedbackPresenter: LessonFeedbackPresentationLogic {
  weak var viewController: LessonFeedbackDisplayLogic?

  // MARK: Do something
    func showRateExperienceWith(categoryName: String?) {
        viewController?.showExperienceWith(categoryName: categoryName)
    }
    func handle(response: Response<UserResponse>) {
        if response.isSuccess {
            UserDefaults.standard.removeValue(for: .userFeedback)
            viewController?.goBackToLessonList()
        } else {
            let msg  = NetworkManager.shared.errorString(from: response) ?? .failedTo(.lessonFeedback) + "\n" + .tryAgainInTime
            viewController?.showAlertFor(text: msg)
        }
    }
    func showError(text: String) {
        viewController?.showAlertFor(text: text)
    }
}
