//
//  LessonFeedbackRouter.swift
//  PLAN-IT
//
//  Created by KiwiTech on 09/08/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LessonFeedbackRoutingLogic {
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol LessonFeedbackDataPassing {
  var dataStore: LessonFeedbackDataStore? { get set}
}

class LessonFeedbackRouter: NSObject, LessonFeedbackRoutingLogic, LessonFeedbackDataPassing {
  weak var viewController: LessonFeedbackViewController?
  var dataStore: LessonFeedbackDataStore?
}
