//
//  LessonFeedbackInteractor.swift
//  PLAN-IT
//
//  Created by KiwiTech on 09/08/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LessonFeedbackBusinessLogic {
    func showExperienceOfCategory()
    func sendFeedback(with request: LessonFeedback.Request)
}

protocol LessonFeedbackDataStore {
    var categoryName: String? { get set }
    var lessonId: Int { get set }
}

class LessonFeedbackInteractor: LessonFeedbackBusinessLogic, LessonFeedbackDataStore {

    var presenter: LessonFeedbackPresentationLogic?
    var worker: LessonFeedbackWorker?
    var categoryName: String? = ""
    var lessonId: Int = 0

    // MARK: Do something

    func showExperienceOfCategory() {
        presenter?.showRateExperienceWith(categoryName: categoryName)
    }
    func sendFeedback(with request: LessonFeedback.Request) {
        if worker == nil {
            worker = LessonFeedbackWorker()
        }
        do {
            try worker?.sendFeedback(request: request, completion: { [weak self] (response) in
                self?.presenter?.handle(response: response)
            })
        } catch let exception {
            handle(exception: exception)
        }
    }
    fileprivate func handle(exception: Error) {
        presenter?.showError(text: .somethingWentWrong + "\n" + .tryAgainInTime)
    }
}
