//
//  BudgetSavingModels.swift
//  PLAN-IT
//
//  Created by KiwiTech on 29/08/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
enum BudgetSaving {
  // MARK: Use cases
    struct Request: ParameterConvertible {
        var categoryId: Int?
        var percentage: Float?
        init(categoryId: Int? = nil, percentage: Float? = nil) {
           self.categoryId = categoryId
           self.percentage = percentage
        }
    }
    struct Response {
    }
    struct ViewModel {
    }
}
