//
//  BudgetSavingPresenter.swift
//  PLAN-IT
//
//  Created by KiwiTech on 29/08/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
protocol BudgetSavingPresentationLogic {
    func showError(text: String)
    func handle(response: Response<BudgetCategoryResponse>)
    func handleBudgetCategoryDetail(response: Response<StaticMessgaeResponse>)
}
class BudgetSavingPresenter: BudgetSavingPresentationLogic {
    weak var viewController: BudgetSavingDisplayLogic?
    // MARK: Do something
    func showError(text: String) {
        viewController?.showAlertFor(text: text)
    }
    func handle(response: Response<BudgetCategoryResponse>) {
        if response.isSuccess, let value = response.value {
            viewController?.fetchBudgetCategory(data: value.data)
        } else {
            let msg = NetworkManager.shared.errorString(from: response)
            viewController?.showAlertFor(text: msg ?? .failedTo(.proceed) + "\n" + .tryAgainInTime)
        }
    }
    func handleBudgetCategoryDetail(response: Response<StaticMessgaeResponse>) {
        if response.isSuccess, let value = response.value {
            viewController?.fetchBudgetCategoryDetail(data: value.data)
        } else {
            let msg = NetworkManager.shared.errorString(from: response)
            viewController?.showAlertFor(text: msg ?? .failedTo(.proceed) + "\n" + .tryAgainInTime)
        }
    }
}
