//
//  BudgetSavingRouter.swift
//  PLAN-IT
//
//  Created by KiwiTech on 29/08/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol BudgetSavingRoutingLogic {
}

protocol BudgetSavingDataPassing {
  var dataStore: BudgetSavingDataStore? { get }
}

class BudgetSavingRouter: NSObject, BudgetSavingRoutingLogic, BudgetSavingDataPassing {
  weak var viewController: BudgetSavingViewController?
  var dataStore: BudgetSavingDataStore?
}
