//
//  BudgetSavingInteractor.swift
//  PLAN-IT
//
//  Created by KiwiTech on 29/08/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BudgetSavingBusinessLogic {
    func fetchBudgetCategory()
    func fetchBudgetCategoryDetail(request: BudgetSaving.Request)
}

protocol BudgetSavingDataStore {
    //var name: String { get set }
}

class BudgetSavingInteractor: BudgetSavingBusinessLogic, BudgetSavingDataStore {
    var presenter: BudgetSavingPresentationLogic?
    var worker: BudgetSavingWorker?
    // MARK: Do something
    func fetchBudgetCategory() {
        if worker == nil {
            worker = BudgetSavingWorker()
        }
        do {
            try worker?.fetchBudgetCategory(completion: {[weak self] (response) in
                self?.presenter?.handle(response: response)
            })
        } catch let error {
            handle(exception: error)
        }
    }
    func fetchBudgetCategoryDetail(request: BudgetSaving.Request) {
        if worker == nil {
            worker = BudgetSavingWorker()
        }
        do {
            try worker?.fetchBudgetCategoryDetail(request: request, completion: {[weak self] (response) in
                self?.presenter?.handleBudgetCategoryDetail(response: response)
            })
        } catch let error {
            handle(exception: error)
        }
    }
    fileprivate func handle(exception: Error) {
        presenter?.showError(text: .somethingWentWrong + "\n" + .tryAgainInTime)
    }
}
