//
//  SetBudgetInteractor.swift
//  PLAN-IT
//
//  Created by KiwiTech on 27/08/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SetBudgetBusinessLogic {
    func setBudget(request: SetBudget.Request)
    func fetchCategoryDescription()
}

protocol SetBudgetDataStore {
    var description: String? { get set }
    var category: BudgetCategory? { get set }
}

class SetBudgetInteractor: SetBudgetBusinessLogic, SetBudgetDataStore {
    var description: String?
    var category: BudgetCategory?
    var presenter: SetBudgetPresentationLogic?
    var worker: SetBudgetWorker?
    // MARK: Do something
    func setBudget(request: SetBudget.Request) {
        if worker == nil {
            worker = SetBudgetWorker()
        }
        do {
            try worker?.setBudget(request: request, completion: {[weak self] (response) in
                self?.presenter?.handleSetBudget(response: response)
            })
        } catch let error {
            handle(exception: error)
        }
    }
    fileprivate func handle(exception: Error) {
        presenter?.showError(text: .somethingWentWrong + "\n" + .tryAgainInTime)
    }
    func fetchCategoryDescription() {
        presenter?.fetchCategoryDescription(data: description, category: category)
    }
}
