//
//  SetBudgetRouter.swift
//  PLAN-IT
//
//  Created by KiwiTech on 27/08/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SetBudgetRoutingLogic {
}

protocol SetBudgetDataPassing {
  var dataStore: SetBudgetDataStore? { get set }
}

class SetBudgetRouter: NSObject, SetBudgetRoutingLogic, SetBudgetDataPassing {
  weak var viewController: SetBudgetViewController?
  var dataStore: SetBudgetDataStore?
}
