//
//  SetBudgetPresenter.swift
//  PLAN-IT
//
//  Created by KiwiTech on 27/08/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
protocol SetBudgetPresentationLogic {
    func showError(text: String)
    func handleSetBudget(response: Response<UserResponse>)
    func fetchCategoryDescription(data: String?, category: BudgetCategory?)
}

class SetBudgetPresenter: SetBudgetPresentationLogic {
    weak var viewController: SetBudgetDisplayLogic?
    func showError(text: String) {
        viewController?.showAlertFor(text: text)
    }
    func handleSetBudget(response: Response<UserResponse>) {
        if response.isSuccess, let value = response.value {
            viewController?.setBudget(data: value.detail)
        } else {
            let msg = NetworkManager.shared.errorString(from: response)
            viewController?.showAlertFor(text: msg ?? .failedTo(.proceed) + "\n" + .tryAgainInTime)
        }
    }
    func fetchCategoryDescription(data: String?, category: BudgetCategory?) {
        viewController?.fetchCategoryDescription(data: data, category: category)
    }
}
