//
//  SetBudgetModels.swift
//  PLAN-IT
//
//  Created by KiwiTech on 27/08/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
enum SetBudget {
  // MARK: Use cases
    struct Request: ParameterConvertible {
        var categoryId: Int?
        var budget: Float?
        var nextMonthBudget: Float?
        init(categoryId: Int? = nil, budget: Float? = nil, nextMonthBudget: Float? = nil) {
            self.categoryId = categoryId
            self.budget = budget
            self.nextMonthBudget = nextMonthBudget
        }
    }
    struct Response {
    }
    struct ViewModel {
    }
}
