//
//  TermsPrivacyPresenter.swift
//  PLAN-IT
//
//  Created by KiwiTech on 07/08/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
protocol TermsPrivacyPresentationLogic {
    func showError(text: String)
    func handle(response: Response<TermsPolicyResponse>)
}

class TermsPrivacyPresenter: TermsPrivacyPresentationLogic {
  weak var viewController: TermsPrivacyDisplayLogic?
    func showError(text: String) {
        viewController?.showAlertFor(text: text)
    }
    func handle(response: Response<TermsPolicyResponse>) {
        if response.isSuccess, let value = response.value {
            viewController?.fetchedUrls(data: value.data)
        } else {
            let msg = NetworkManager.shared.errorString(from: response)
            viewController?.showAlertFor(text: msg ?? .failedTo(.proceed) + "\n" + .tryAgainInTime)
        }
    }
}
