//
//  TermsPrivacyRouter.swift
//  PLAN-IT
//
//  Created by KiwiTech on 07/08/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol TermsPrivacyRoutingLogic {
}

protocol TermsPrivacyDataPassing {
  var dataStore: TermsPrivacyDataStore? { get }
}

class TermsPrivacyRouter: NSObject, TermsPrivacyRoutingLogic, TermsPrivacyDataPassing {
  weak var viewController: TermsPrivacyViewController?
  var dataStore: TermsPrivacyDataStore?
}
