//
//  TermsPrivacyWorker.swift
//  PLAN-IT
//
//  Created by KiwiTech on 07/08/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
class TermsPrivacyWorker {
    let apiStore = TermsPrivacyApiStore()
    func getUrls(completion: @escaping Completion<TermsPolicyResponse>) throws {
        apiStore.getUrls(completion: completion)
    }
}
