//
//  TermsPrivacyInteractor.swift
//  PLAN-IT
//
//  Created by KiwiTech on 07/08/19.
//  Copyright (c) 2019 KiwiTech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TermsPrivacyBusinessLogic {
  func getUrls()
}

protocol TermsPrivacyDataStore {
  //var name: String { get set }
}

class TermsPrivacyInteractor: TermsPrivacyBusinessLogic, TermsPrivacyDataStore {
  var presenter: TermsPrivacyPresentationLogic?
  var worker: TermsPrivacyWorker?
    func getUrls() {
        if worker == nil {
            worker = TermsPrivacyWorker()
        }
        do {
            try worker?.getUrls(completion: {[weak self] (response) in
                self?.presenter?.handle(response: response)
            })
        } catch let error {
            handle(exception: error)
        }
    }
    fileprivate func handle(exception: Error) {
        presenter?.showError(text: .somethingWentWrong + "\n" + .tryAgainInTime)
    }
}
